import { Injectable } from '@angular/core';

@Injectable()
export class GlobalService {
    readonly myt_url: string = ' global service is working';

    private END_POINT: string = 'http://www.ta-meteo.fr/api/';

    public url = {
        'countries': this.END_POINT + 'countries',
        'localization': this.END_POINT + 'localization',
        'weather_three_hours': this.END_POINT + 'weatherCity3hours',
        'weather_forteen_days': this.END_POINT + 'weatherCity14Days',
    }

    public forms = {
        'nbre_retry': 'Nombre de tentative de connexion possibles:',
        'unlimited': 'Nombre de tentative de connexion illimité:',
        'duration': 'Durée d\'attente pour autoriser la connexion de nouveau:',
        'login': 'Login',
        'enable_date': 'Date de verouillage du compte',
        'disable_date': 'Date de déverrouillage prévue',
        'unlock': 'Déverrouiller',
        'legal_information': 'Renseignements juridiques',
        'head_office': 'Siège social',
        'contact_contract': 'Contact administratif pour le contrat',
        'contact_billing': 'Contact administratif pour la facturation',
        'company_name': 'Raison sociale(*):',
        'company_legal_form': 'Forme juridique(*):',
        'company_capital': 'Au capital de:',
        'company_rcs': 'RCS:',
        'company_rcs_city': 'Ville d\'immatriculation:',
        'company_siret': 'Sous le n°Siret (14 chiffres):',
        'company_naf': 'N°APE / Code NAF:',
        'company_tva': 'TVA Intracommunautaire:',
        'company_manager': 'Prénom & nom resprésentant:',
        'company_manager_name': 'Qualité du représentant:',
        'register': 'Enregistrer',
        'headOffice_adress': 'Adresse du siège social:',
        'headOffice_standard': 'Standard du siège social:',
        'headOffice_fax': 'Téléphone du siège social:',
        'headOffice_in': 'Chez:',
        'headOffice_building': 'Batiment:',
        'headOffice_residence': 'Résidence:',
        'headOffice_num': 'Numero:',
        'headOffice_type': 'Type de voie:',
        'headOffice_name': 'Nom de la voie:',
        'headOffice_code': 'Code postal:',
        'headOffice_city': 'Ville (*):',
        'headOffice_country': 'Pays (*):',
        'headOffice_extra': 'Informationscomplémentaires:',
        'cancel': 'Annuler',
        'contract_first_name': 'Prénom du contact',
        'contract_last_name': 'Nom du contrat:',
        'contact_email': 'E-mail du contrat:',
        'contact_mobile': 'Numéro mobile:',
        'contact_phone': 'Numéro fixe:',
        'billing_first_name': 'Prénom du contact',
        'billing_last_name': 'Nom du contrat:',
        'billing_email': 'E-mail du professionnel:',
        'billing_mobile': 'Numéro mobile:',
        'billing_phone': 'Numéro fixe:',
        'mobile_billing_adress': 'Adresse de facturaion:',
        'billing_post_code': 'Code postal:',
        'billing_city': 'ville:',
        'billing_country': 'Pays:',
        'billing_extra': 'Informations complémentaires:',
        'add_contact': 'Ajouter une fiche client',
        'export_contacts': 'Exporter la liste des clients',
        'import_contacts': 'Importer',
        'type': 'Type',
        'contact_company_name': 'Raison Sociale',
        'display': 'Consulter',
        'duplicate': 'Dupliquer',
        'update': 'Modifier',
        'delete': 'Supprimer',
        'user_name': 'Nom de l\'utilisateur:',
        'add': 'Ajouter',
        'first_name': 'Nom',
        'last_name': 'Prénom',
        'email_adresse': 'Adresse e-mail',
        'profil': 'Profil',
        'profile': 'Profil',
        'create_date': 'Date de création',
        'update_date': 'Date de modification',
        'start_date': 'Date de début',
        'end_date': 'Date de fin',
        'status': 'Statut',
        'active': 'Actif',
        'yes': 'Oui',
        'no': 'Non',
        'search': 'Recherche...',
        'start_date_d': 'Date de début:',
        'end_date_d': 'Date de fin:',
        'delegate': 'Déléguer',
        'close': 'Fermer',
        'id': 'ID',
        'delegation_details': 'Détails de la délégation :',
        'id_d': 'ID:',
        'first_name_d': 'Nom:',
        'last_name_d': 'Prénom(*):',
        'profile_d': 'Profil(*):',
        'create_date_d': 'Date de création:',
        'update_date_d': 'Date de modification:',
        'accept': 'Accepter',
        'refuse': 'Refuser',
        'return': 'Retour',
        'group_name': 'Nom du groupe',
        'scale': 'Echelle',
        'created_by': 'Créé par',
        'users': 'Users',
        'add_customer': 'Ajouter une fiche client',
        'export_customers': 'Exporter la liste des clients',
        'import': 'Importer',
        'created_by_d': 'Créé par:',
        'scale_d': 'Echelle:',
        'email': 'Email:',
        'added_date': 'Date d\'ajout',
        'remove': 'Retirer',
        'enter_mail': 'Saisir son adresse e-mail',
        'adress_mail': 'Adresse e-mail',
        'create': 'Créer',
        'please_login': 'Veuillez vous authentifier',
        'login_required': 'Le login est obligatoire',
        'email_required': 'L\'adresse email est obligatoire',
        'login_must_contain': 'Le login doit contenir au moins 8 caractère',
        'password_required': 'Le mot de passe est obligatoire',
        'password': 'Mot de passe(*):',
        'password_must_contain': 'Le mot de passe doit contenir au moins 6 caractère',
        'stay_connected': 'Rester connecté',
        'password_forgetten': 'Mot de passe oublié?',
        'connection': 'Connexion',
        'rights_reserved': '@2017 All Rights Reserved',
        'connection_error': 'Erreur de connexion',
        'nbre_archived': 'Nombre de versions à archiver:',
        'archive_all': 'Tout archiver:',
        'apply': 'Appliquer',
        'add_user': 'Ajouter un  utilisateur',
        'export_users': 'Exporter la liste des utilsateurs',
        'regenerate_pwd': 'Regénéer le mot de passe',
        'user_id': 'User ID:',
        'personnel': 'Personnel',
        'contacts': 'Contacts',
        'company': 'Société',
        'responsible': 'Responsables',
        'internal_contract': 'Contrat interne',
        'nationality': 'Nationalité:',
        'birth_name': 'Nom de naissance(*):',
        'birth_date': 'Date de naissance:',
        'birth_place': 'Lieu de naissance:',
        'birth_country': 'Pays de naissance:',
        'civility': 'Civilité:',
        'kind': 'Genre:',
        'add_responsible': 'Ajouter un responsable',
        'delete_lines': 'Supprimer des lignes',
        'next': 'Suivant',
        'password_forgetten_title': 'Veuillez saisir l\'adresse e-mail de votre compte',
        'cra': 'Compte rendu des activités',
        'mois': 'Mois',
        'nbr_jours': 'Jours ouvrés',
        'icon': 'Icone',
        'description': 'Description',
        'libelle': 'Libellé',
        'add_module': 'Ajouter un  module',
        'nom_profil': 'Nom du profil',
        'add_menu': 'Ajouter un menu',
        'titre': 'Titre',
        'lien': 'Lien',
        'subMenu': 'Sous Menus(ID)',
        'ordre': 'Ordre',
        'email_groupe': 'E-mail du groupe:',
        'list_user': 'Liste des utilisateurs',
        'ts_waiting_validation': 'En cours de validation',
        'ts_valide': 'Validé',
        'ts_refuse': 'Refusé',
        'ts_validate': 'Envoi pour validation',
        'annee': 'Année',
        'add_holiday': 'Ajouter un jour férié',
        'contract_Type': 'Type du contrat',
        'contract_Client': 'Client/Prestataire',
        'contract_title': 'Titre du contrat',
        'contract_TJM': 'TJM/HT',
        'contract_currency': 'Devise',
        'contract_Benefits': 'Prix des prestations',
        'contract_belling': 'Modalités de paiement',
        'contract_portion': 'Tranche de paiement',
        'c_portion': 'Les tranches',
        'add_contract': 'Ajout d\'un contrat',
        'required': 'Ce champ est obligatoire',
        'date_error': 'la date de fin doit être postérieure à la date de début'
    };


}